"""T3 - StartSessionBody refactor + ULID backend generation + client_request_id idempotency.

D13: POST /research/start body changed from {session_id} to {query};
     session_id is now generated by the backend as a ULID.
D13.5: client_request_id optional field, 60s short-window idempotency key:
       same client_request_id within 60s -> 200 + same session_id (no new session).

All tests use TestClient(app) lifespan; env_settings fixture injects required env vars.
"""

from __future__ import annotations

import re
import time
from collections.abc import Iterator
from pathlib import Path

import pytest
from cachetools import TTLCache
from fastapi.testclient import TestClient

# ULID 26-char format: Crockford Base32 (0-9 and A-Z excluding I, L, O, U)
_ULID_RE = re.compile(r"^[0-9A-HJKMNP-TV-Z]{26}$")


@pytest.fixture(autouse=True)
def clear_idempotency_cache() -> Iterator[None]:
    """Clear module-level idempotency cache and lock pool before/after each test.

    Both _IDEMPOTENCY_CACHE and _IDEMPOTENCY_LOCKS must be cleared together so
    tests that monkeypatch the cache do not leave stale locks referencing the old
    TTLCache instance (which would prevent the TOCTOU lock from being acquired).
    """
    from app.routers import research as research_mod

    research_mod._IDEMPOTENCY_CACHE.clear()
    research_mod._IDEMPOTENCY_LOCKS.clear()
    yield
    research_mod._IDEMPOTENCY_CACHE.clear()
    research_mod._IDEMPOTENCY_LOCKS.clear()


# ---------------------------------------------------------------------------
# Body schema tests (5 tests)
# ---------------------------------------------------------------------------


def test_start_session_body_query_required(env_settings: Path) -> None:
    """Empty body -> 422: query field is required."""
    from main import app

    with TestClient(app) as client:
        r = client.post("/api/research/start", json={})
    assert r.status_code == 422


def test_start_session_body_query_too_short(env_settings: Path) -> None:
    """query="" (min_length=1) -> 422."""
    from main import app

    with TestClient(app) as client:
        r = client.post("/api/research/start", json={"query": ""})
    assert r.status_code == 422


def test_start_session_body_query_too_long(env_settings: Path) -> None:
    """query over 2000 chars -> 422."""
    from main import app

    with TestClient(app) as client:
        r = client.post("/api/research/start", json={"query": "x" * 2001})
    assert r.status_code == 422


def test_start_session_returns_201_with_session_id(env_settings: Path) -> None:
    """Valid request -> 201; response contains session_id in 26-char ULID format."""
    from main import app

    with TestClient(app) as client:
        r = client.post("/api/research/start", json={"query": "AI trends"})
    assert r.status_code == 201
    data = r.json()
    assert "session_id" in data
    assert _ULID_RE.match(data["session_id"]), (
        f"session_id not in ULID format: {data['session_id']!r}"
    )


def test_start_session_old_body_format_rejected(env_settings: Path) -> None:
    """Old format {session_id: 'old-id'} -> 422 (query field absent, session_id not in body)."""
    from main import app

    with TestClient(app) as client:
        r = client.post("/api/research/start", json={"session_id": "old-id"})
    assert r.status_code == 422


# ---------------------------------------------------------------------------
# Idempotency tests (4 tests) - D13.5
# ---------------------------------------------------------------------------


def test_start_session_idempotency_returns_same_session_id_within_window(
    env_settings: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Same client_request_id within 60s window -> returns same session_id; second call 200 not 201."""
    from app.routers import research as research_mod
    from main import app

    # Use a longer TTL to ensure window does not expire during test
    monkeypatch.setattr(
        research_mod,
        "_IDEMPOTENCY_CACHE",
        TTLCache(maxsize=1024, ttl=60.0),
    )

    crid = "test-idem-001"
    with TestClient(app) as client:
        r1 = client.post(
            "/api/research/start",
            json={"query": "idempotency test", "client_request_id": crid},
        )
        assert r1.status_code == 201
        sid1 = r1.json()["session_id"]

        r2 = client.post(
            "/api/research/start",
            json={"query": "idempotency test", "client_request_id": crid},
        )
    assert r2.status_code == 200
    sid2 = r2.json()["session_id"]
    assert sid1 == sid2, f"idempotency hit should return same session_id, but {sid1!r} != {sid2!r}"


def test_start_session_idempotency_outside_window_creates_new_session(
    env_settings: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """After TTL expiry, same client_request_id creates a new session_id."""
    from app.routers import research as research_mod
    from main import app

    # TTL=0.1s so cache expires quickly
    monkeypatch.setattr(
        research_mod,
        "_IDEMPOTENCY_CACHE",
        TTLCache(maxsize=1024, ttl=0.1),
    )

    crid = "test-idem-002"
    with TestClient(app) as client:
        r1 = client.post(
            "/api/research/start",
            json={"query": "expiry idempotency test", "client_request_id": crid},
        )
        assert r1.status_code == 201
        sid1 = r1.json()["session_id"]

        # Wait for TTL to expire
        time.sleep(0.2)

        r2 = client.post(
            "/api/research/start",
            json={"query": "expiry idempotency test", "client_request_id": crid},
        )
    assert r2.status_code == 201
    sid2 = r2.json()["session_id"]
    assert sid1 != sid2, f"after TTL expiry should create new session_id, but both: {sid1!r}"


def test_start_session_no_client_request_id_creates_new_session_each_time(
    env_settings: Path,
) -> None:
    """Without client_request_id, each POST creates a new session_id."""
    from main import app

    with TestClient(app) as client:
        r1 = client.post("/api/research/start", json={"query": "no idempotency key test"})
        assert r1.status_code == 201
        sid1 = r1.json()["session_id"]

        r2 = client.post("/api/research/start", json={"query": "no idempotency key test"})
        assert r2.status_code == 201
        sid2 = r2.json()["session_id"]

    assert sid1 != sid2, (
        f"without client_request_id each call should create different session_id: {sid1!r} == {sid2!r}"
    )


def test_start_session_invalid_client_request_id_format_returns_422(
    env_settings: Path,
) -> None:
    """client_request_id with special chars -> 422 (pattern validation failure)."""
    from main import app

    with TestClient(app) as client:
        # Contains spaces and special characters
        r = client.post(
            "/api/research/start",
            json={"query": "test", "client_request_id": "invalid id!@#"},
        )
    assert r.status_code == 422


# ---------------------------------------------------------------------------
# Manager signature tests (2 tests)
# ---------------------------------------------------------------------------


async def test_session_manager_start_session_passes_query_to_db(
    initialized_db: Path,
) -> None:
    """start_session(session_id=..., query=...) should persist query to DB."""
    import asyncio

    import aiosqlite

    from app.services.langgraph_service import LangGraphStub
    from app.services.session_manager import SessionManager

    sm = SessionManager(db_path=str(initialized_db), langgraph=LangGraphStub())
    await sm.start_session(session_id="q-test-1", query="test query content")

    async with aiosqlite.connect(str(initialized_db)) as c:
        cursor = await c.execute(
            "SELECT query FROM lumen_research_sessions WHERE id = ?",
            ("q-test-1",),
        )
        row = await cursor.fetchone()

    assert row is not None
    assert row[0] == "test query content", f"DB query column mismatch: {row[0]!r}"

    # Wait for task completion to avoid pending tasks after test ends
    if "q-test-1" in sm.active_runs:
        await asyncio.wait_for(sm.active_runs["q-test-1"], timeout=2.0)
        await asyncio.sleep(0.05)


def test_session_manager_start_session_requires_keyword_args() -> None:
    """start_session signature enforces keyword-only (*) - positional call should TypeError."""
    import inspect

    from app.services.session_manager import SessionManager

    sig = inspect.signature(SessionManager.start_session)
    params = list(sig.parameters.values())

    # Skip self; remaining params should all be KEYWORD_ONLY
    non_self = [p for p in params if p.name != "self"]
    for p in non_self:
        assert p.kind == inspect.Parameter.KEYWORD_ONLY, (
            f"param {p.name!r} should be KEYWORD_ONLY, got: {p.kind}"
        )
