"""Research router.

T3 v2.3 - D13 + D13.5:

POST /research/start body: { query: str(1-2000), client_request_id: Optional[str] }
- session_id generated by backend ULID (D13: avoids frontend ULID conflicts, cleaner path semantics)
- client_request_id provides 60s short-window idempotency (D13.5: prevents orphan sessions
  from network retries / double-clicks / lost responses)

GET /research/{session_id}/stream - W3C SSE replay + live channel (T10 unchanged).
"""

from __future__ import annotations

import asyncio
import re
import secrets
from typing import Annotated

import aiosqlite
from cachetools import TTLCache
from fastapi import APIRouter, Header, HTTPException, Path, Request, Response, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from ulid import ULID

from app.core.config import Settings
from app.core.deps import get_settings
from app.core.sse import stream_session
from app.db.sqlite import configure_connection, lookup_seq_by_event_id
from app.services.inject_directive import (
    InjectCloseAfterDirective,
    InjectDirective,
    InjectErrorDirective,
)
from app.services.session_manager import (
    SessionAlreadyRunningError,
    SessionManager,
)

router = APIRouter(prefix="/research", tags=["research"])

# D13.5: in-memory LRU + TTL idempotency cache (single-worker ADR-0001 D5).
# {client_request_id: session_id}, TTL 60s, max 1024 entries.
# Exposed at module level so tests can monkeypatch/clear it.
_IDEMPOTENCY_CACHE: TTLCache[str, str] = TTLCache(maxsize=1024, ttl=60.0)

# Per-key asyncio.Lock pool — prevents TOCTOU race when concurrent requests share
# the same client_request_id. TTL 60s matches idempotency window; auto-expires
# stale locks so the dict does not grow unboundedly.
_IDEMPOTENCY_LOCKS: TTLCache[str, asyncio.Lock] = TTLCache(maxsize=1024, ttl=60.0)

# T11 D-TM: ephemeral inject_directive store keyed by session_id, populated
# by POST /start when test request validates double-guard. GET /stream
# reads it to drive stream_session's early-close behavior. TTL 5min covers
# session lifetime; no cross-session pollution because each entry is keyed
# by unique session_id.
_INJECT_DIRECTIVES: TTLCache[str, InjectDirective] = TTLCache(maxsize=1024, ttl=300.0)


def _is_test_request(request: Request, settings: Settings) -> bool:
    """Double-guard testing-mode check (D-TM v2.1).

    Returns True only when ALL conditions hold:
    1. settings.TESTING_MODE is True (env: LUMEN_TESTING_MODE=true)
    2. settings.TESTING_TOKEN is not None (env: LUMEN_TESTING_TOKEN=<value>)
    3. request has X-Lumen-Test-Token header
    4. header value matches settings.TESTING_TOKEN.get_secret_value() via
       secrets.compare_digest (constant-time, prevents timing attack)

    Returns False otherwise. Production never enables TESTING_MODE.
    """
    if not settings.TESTING_MODE:
        return False
    if settings.TESTING_TOKEN is None:
        return False
    header = request.headers.get("X-Lumen-Test-Token")
    if header is None:
        return False
    return secrets.compare_digest(header, settings.TESTING_TOKEN.get_secret_value())


# Strict regex: prefix uses only ASCII alphanumerics + colons/underscores
# in a fixed shape; the (.*) tail captures the rest of the query verbatim
# (re.DOTALL so newlines in the user's query are preserved).
_INJECT_CLOSE_AFTER_RE = re.compile(r"^__inject_close_after:(\d{1,3})__(.*)$", re.DOTALL)
_INJECT_ERROR_RE = re.compile(r"^__inject_error__(.*)$", re.DOTALL)


def _parse_inject_directive(query: str) -> tuple[InjectDirective | None, str]:
    """Parse query for testing prefix; return (directive, clean_query).

    NN2 (v2.1): strips prefix from clean_query so audit_log + LangGraph
    nodes never see the testing prefix literal (would otherwise pollute
    LLM output / DB query column).
    NNN3 (v2.2): InjectCloseAfterDirective.n bounded to [1, 100]; out-of-range
    treated as malformed (returns None directive + original query unchanged).

    Returns:
        (None, query) if no prefix matches (production path).
        (InjectCloseAfterDirective(n), clean_query) for __inject_close_after:N__
            where 1 <= N <= 100.
        (InjectErrorDirective(), clean_query) for __inject_error__.
        (None, query) for malformed prefix (treated as plain query).

    Pure parser — does NOT enforce TESTING_MODE guard. Caller must guard
    via _is_test_request before passing user input to this function.
    """
    m = _INJECT_CLOSE_AFTER_RE.match(query)
    if m:
        n = int(m.group(1))
        if 1 <= n <= 100:
            return InjectCloseAfterDirective(n=n), m.group(2)
        return None, query  # n out of bound -> malformed, treat as normal
    m = _INJECT_ERROR_RE.match(query)
    if m:
        return InjectErrorDirective(), m.group(1)
    return None, query


class StartSessionBody(BaseModel):
    """D13 v2.3: body changed from {session_id} to {query}; session_id generated by backend."""

    query: str = Field(min_length=1, max_length=2000)
    client_request_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[a-zA-Z0-9_-]{1,64}$",
    )


class StartSessionResponse(BaseModel):
    session_id: str


@router.post(
    "/start",
    status_code=status.HTTP_201_CREATED,
    response_model=StartSessionResponse,
)
async def start_session(
    body: StartSessionBody,
    request: Request,
    response: Response,
) -> StartSessionResponse:
    """D13 + D13.5: backend ULID + per-client idempotency with TOCTOU lock.

    Status codes:
    - 201 Created: new session established
    - 200 OK: idempotency hit, returns existing session_id (no new session)
    - 409 Conflict: session_id already running (ULID collisions theoretical; safety net only)
    - 422 Unprocessable Entity: query / client_request_id validation failure
    """
    session_manager: SessionManager = request.app.state.session_manager

    # T11 D-TM: resolve inject directive before branching on client_request_id.
    # _is_test_request enforces double-guard; _parse_inject_directive strips
    # prefix from clean_query (NN2) so DB / LangGraph never see the test prefix.
    directive: InjectDirective | None = None
    clean_query: str = body.query
    if _is_test_request(request, get_settings()):
        directive, clean_query = _parse_inject_directive(body.query)

    # No client_request_id: no idempotency, create directly.
    if body.client_request_id is None:
        session_id = str(ULID())
        try:
            await session_manager.start_session(session_id=session_id, query=clean_query)
        except SessionAlreadyRunningError as exc:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Session {exc.session_id!r} is already running",
            ) from None
        if directive is not None:
            _INJECT_DIRECTIVES[session_id] = directive
        return StartSessionResponse(session_id=session_id)

    # Has client_request_id: per-key lock wraps read-await-write to prevent TOCTOU.
    # Concurrent requests with the same key block here; the second sees the cache hit
    # and returns 200 without creating a new session.
    lock = _IDEMPOTENCY_LOCKS.get(body.client_request_id)
    if lock is None:
        lock = asyncio.Lock()
        _IDEMPOTENCY_LOCKS[body.client_request_id] = lock

    async with lock:
        # Check inside lock (TOCTOU-safe).
        existing = _IDEMPOTENCY_CACHE.get(body.client_request_id)
        if existing is not None:
            response.status_code = status.HTTP_200_OK
            return StartSessionResponse(session_id=existing)

        # Create inside lock: concurrent same-key requests are serialized.
        session_id = str(ULID())
        try:
            await session_manager.start_session(session_id=session_id, query=clean_query)
        except SessionAlreadyRunningError as exc:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Session {exc.session_id!r} is already running",
            ) from None
        _IDEMPOTENCY_CACHE[body.client_request_id] = session_id
        if directive is not None:
            _INJECT_DIRECTIVES[session_id] = directive

    return StartSessionResponse(session_id=session_id)


@router.get("/{session_id}/stream")
async def stream_session_endpoint(
    session_id: Annotated[str, Path(min_length=1, max_length=64)],
    last_event_id: Annotated[str | None, Header(alias="Last-Event-ID")] = None,
) -> StreamingResponse:
    """W3C SSE channel: replay-then-live for a research session.

    Pre-flight:
      - 404 if the session_id has no row in `lumen_research_sessions`
      - 400 if `Last-Event-ID` is provided but unknown (we don't
        silently replay-from-zero — the client MUST acknowledge a
        missing cursor)

    Headers:
      - Content-Type: text/event-stream
      - Cache-Control: no-cache (forbid intermediary caching)
      - X-Accel-Buffering: no (disable nginx response buffering — SSE
        frames must flush as soon as written)

    The endpoint never spawns a LangGraph producer (read-only path);
    the producer is owned by `POST /start` exclusively. A GET on a
    terminal session returns a finite replay then closes.
    """
    settings = get_settings()
    db_path = settings.LUMEN_DB_PATH

    last_seq = 0
    async with aiosqlite.connect(db_path) as conn:
        await configure_connection(conn)
        cur = await conn.execute(
            "SELECT 1 FROM lumen_research_sessions WHERE id = ?",
            (session_id,),
        )
        if (await cur.fetchone()) is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"session {session_id!r} not found",
            )
        # `is not None` (not truthiness): an empty header value `Last-Event-ID:`
        # means "provided but malformed", which is a client bug we surface as
        # 400 — silently falling back to last_seq=0 would misrepresent the
        # contract documented in this endpoint's docstring.
        if last_event_id is not None:
            stripped = last_event_id.strip()
            if not stripped:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Last-Event-ID header is present but empty",
                )
            resolved = await lookup_seq_by_event_id(conn, event_id=stripped)
            if resolved is None:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Unknown Last-Event-ID; client must reconnect without the header",
                )
            last_seq = resolved

    # T11: look up any inject directive stored by POST /start for this session.
    inject_directive = _INJECT_DIRECTIVES.get(session_id)

    return StreamingResponse(
        stream_session(
            session_id=session_id,
            db_path=db_path,
            last_seq=last_seq,
            inject_directive=inject_directive,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
