"""Research router.

T3 v2.3 - D13 + D13.5:

POST /research/start body: { query: str(1-2000), client_request_id: Optional[str] }
- session_id generated by backend ULID (D13: avoids frontend ULID conflicts, cleaner path semantics)
- client_request_id provides 60s short-window idempotency (D13.5: prevents orphan sessions
  from network retries / double-clicks / lost responses)

GET /research/{session_id}/stream - W3C SSE replay + live channel (T10 unchanged).
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import secrets
from collections.abc import AsyncGenerator
from functools import lru_cache
from pathlib import Path
from typing import Annotated, Any

import aiosqlite
from cachetools import TTLCache
from fastapi import APIRouter, Header, HTTPException, Request, Response, status
from fastapi import Path as FastAPIPath
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from ulid import ULID

from app.core.config import Settings
from app.core.deps import get_settings
from app.core.sse import stream_session
from app.db.sqlite import configure_connection, lookup_seq_by_event_id
from app.services.inject_directive import (
    InjectCloseAfterDirective,
    InjectDirective,
    InjectErrorDirective,
)
from app.services.session_manager import (
    SessionAlreadyRunningError,
    SessionManager,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/research", tags=["research"])

# ---------------------------------------------------------------------------
# T13 — Demo replay fixture helpers (ADR-0001 D6 L3)
# ---------------------------------------------------------------------------

_DEMO_FIXTURE_PATH = Path(__file__).resolve().parents[2] / "data" / "demo_session.json"


@lru_cache(maxsize=1)
def _load_demo_session() -> dict[str, Any] | None:
    """Load demo replay fixture; return None on missing OR malformed.

    M1.A: fixture lives at apps/api/data/demo_session.json, generated by
    scripts/prerender_demo_session.py (T13b) before each release. Missing
    fixture means demo URL is disabled (404 on /api/demo-session-id) — not
    an error, just an unconfigured replay channel.

    Malformed includes: invalid JSON, missing required keys (session_id /
    query / events). Logs warning so ops sees it; runtime degrades to
    /demo-session-id 404 + stream falls through to normal path.
    """
    if not _DEMO_FIXTURE_PATH.exists():
        return None
    try:
        raw = json.loads(_DEMO_FIXTURE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        logger.warning("Demo fixture malformed JSON: %s; replay disabled", e)
        return None
    # Schema validation: required top-level keys
    if not isinstance(raw, dict):
        logger.warning("Demo fixture is not an object; replay disabled")
        return None
    for key in ("session_id", "query", "events"):
        if key not in raw:
            logger.warning("Demo fixture missing key %r; replay disabled", key)
            return None
    if not isinstance(raw["events"], list):
        logger.warning("Demo fixture events is not a list; replay disabled")
        return None
    if not isinstance(raw["session_id"], str):
        logger.warning("Demo fixture session_id is not a string; replay disabled")
        return None
    return raw


def _load_demo_session_id() -> str | None:
    """Return demo replay session_id from fixture, or None if not configured."""
    fixture = _load_demo_session()
    return fixture["session_id"] if fixture else None


def _is_demo_request_authorized(request: Request, settings: Settings) -> bool:
    """Three-tier guard for demo replay (ADR-0001 D6 L3 + Codex N5):

    1. Referer / Origin in settings.DEMO_ALLOWED_ORIGINS
    2. X-Lumen-Demo-Token header matches settings.DEMO_REPLAY_TOKEN
    3. settings.TESTING_MODE=True AND settings.TESTING_TOKEN is not None
       (mirrors _is_test_request structure; prevents accidental misconfig
       where TESTING_MODE=True alone bypasses guard)

    Any one passes → authorized. None → 403.
    Compares with secrets.compare_digest for the token route to prevent
    timing attacks; origin/referer comparison is set membership.
    """
    # Tier 1: origin/referer allowlist
    origin = request.headers.get("Origin")
    referer = request.headers.get("Referer")
    allowlist = set(settings.DEMO_ALLOWED_ORIGINS)
    if origin and origin in allowlist:
        return True
    if referer:
        # C1: strict prefix match — require "/" boundary to prevent subdomain hijack
        # e.g. "https://demo.lumen.app.evil.com/" must NOT match "https://demo.lumen.app"
        for allowed in allowlist:
            if referer == allowed or referer.startswith(allowed + "/"):
                return True

    # Tier 2: token
    if settings.DEMO_REPLAY_TOKEN is not None:
        token_header = request.headers.get("X-Lumen-Demo-Token")
        if token_header is not None and secrets.compare_digest(
            token_header, settings.DEMO_REPLAY_TOKEN.get_secret_value()
        ):
            return True

    # Tier 3 last: TESTING_MODE bypass — only when TESTING_TOKEN configured
    # (mirrors _is_test_request structure; prevents accidental misconfig where
    # TESTING_MODE=True alone bypasses guard).
    return settings.TESTING_MODE and settings.TESTING_TOKEN is not None


async def _replay_demo_session() -> AsyncGenerator[bytes, None]:
    """Stream demo fixture as W3C SSE frames at 0.1s intervals.

    Defensive: if any event misses required keys (event_id / type), yield
    an error frame and stop. event_id and event_type are stripped of CR/LF
    to prevent SSE-frame-boundary injection (defense-in-depth in case T13b
    prerender output ever includes structurally bad data).
    """
    fixture = _load_demo_session()
    if fixture is None:
        return

    for raw_ev in fixture["events"]:
        if not isinstance(raw_ev, dict):
            logger.warning("Demo fixture event is not an object; aborting replay")
            return
        event_id = raw_ev.get("event_id")
        event_type = raw_ev.get("type")
        if not isinstance(event_id, str) or not isinstance(event_type, str):
            logger.warning(
                "Demo fixture event missing event_id/type; aborting replay"
            )
            return
        # SSE injection defense: strip CR/LF from frame fields
        event_id_safe = event_id.replace("\r", "").replace("\n", "")
        event_type_safe = event_type.replace("\r", "").replace("\n", "")
        # Re-serialize to keep wire invariants (snake_case, no None) consistent
        # with the live producer path. Use json.dumps to avoid pydantic round-trip
        # cost; the fixture is already in canonical wire shape.
        payload = json.dumps(raw_ev, separators=(",", ":"), ensure_ascii=False)
        frame = (
            f"id: {event_id_safe}\nevent: {event_type_safe}\ndata: {payload}\n\n"
        ).encode()
        yield frame
        await asyncio.sleep(0.1)


# D13.5: in-memory LRU + TTL idempotency cache (single-worker ADR-0001 D5).
# {client_request_id: session_id}, TTL 60s, max 1024 entries.
# Exposed at module level so tests can monkeypatch/clear it.
_IDEMPOTENCY_CACHE: TTLCache[str, str] = TTLCache(maxsize=1024, ttl=60.0)

# Per-key asyncio.Lock pool — prevents TOCTOU race when concurrent requests share
# the same client_request_id. TTL 60s matches idempotency window; auto-expires
# stale locks so the dict does not grow unboundedly.
_IDEMPOTENCY_LOCKS: TTLCache[str, asyncio.Lock] = TTLCache(maxsize=1024, ttl=60.0)

# T11 D-TM: ephemeral inject_directive store keyed by session_id, populated
# by POST /start when test request validates double-guard. GET /stream
# reads it to drive stream_session's early-close behavior. TTL 5min covers
# session lifetime; no cross-session pollution because each entry is keyed
# by unique session_id.
_INJECT_DIRECTIVES: TTLCache[str, InjectDirective] = TTLCache(maxsize=1024, ttl=300.0)


def _is_test_request(request: Request, settings: Settings) -> bool:
    """Double-guard testing-mode check (D-TM v2.1).

    Returns True only when ALL conditions hold:
    1. settings.TESTING_MODE is True (env: LUMEN_TESTING_MODE=true)
    2. settings.TESTING_TOKEN is not None (env: LUMEN_TESTING_TOKEN=<value>)
    3. request has X-Lumen-Test-Token header
    4. header value matches settings.TESTING_TOKEN.get_secret_value() via
       secrets.compare_digest (constant-time, prevents timing attack)

    Returns False otherwise. Production never enables TESTING_MODE.
    """
    if not settings.TESTING_MODE:
        return False
    if settings.TESTING_TOKEN is None:
        return False
    header = request.headers.get("X-Lumen-Test-Token")
    if header is None:
        return False
    return secrets.compare_digest(header, settings.TESTING_TOKEN.get_secret_value())


# Strict regex: prefix uses only ASCII alphanumerics + colons/underscores
# in a fixed shape; the (.*) tail captures the rest of the query verbatim
# (re.DOTALL so newlines in the user's query are preserved).
_INJECT_CLOSE_AFTER_RE = re.compile(r"^__inject_close_after:(\d{1,3})__(.*)$", re.DOTALL)
_INJECT_ERROR_RE = re.compile(r"^__inject_error__(.*)$", re.DOTALL)


def _parse_inject_directive(query: str) -> tuple[InjectDirective | None, str]:
    """Parse query for testing prefix; return (directive, clean_query).

    NN2 (v2.1): strips prefix from clean_query so audit_log + LangGraph
    nodes never see the testing prefix literal (would otherwise pollute
    LLM output / DB query column).
    NNN3 (v2.2): InjectCloseAfterDirective.n bounded to [1, 100]; out-of-range
    treated as malformed (returns None directive + original query unchanged).

    Returns:
        (None, query) if no prefix matches (production path).
        (InjectCloseAfterDirective(n), clean_query) for __inject_close_after:N__
            where 1 <= N <= 100.
        (InjectErrorDirective(), clean_query) for __inject_error__.
        (None, query) for malformed prefix (treated as plain query).

    Pure parser — does NOT enforce TESTING_MODE guard. Caller must guard
    via _is_test_request before passing user input to this function.
    """
    m = _INJECT_CLOSE_AFTER_RE.match(query)
    if m:
        n = int(m.group(1))
        if 1 <= n <= 100:
            return InjectCloseAfterDirective(n=n), m.group(2)
        return None, query  # n out of bound -> malformed, treat as normal
    m = _INJECT_ERROR_RE.match(query)
    if m:
        return InjectErrorDirective(), m.group(1)
    return None, query


class DemoSessionIdResponse(BaseModel):
    session_id: str


class StartSessionBody(BaseModel):
    """D13 v2.3: body changed from {session_id} to {query}; session_id generated by backend."""

    query: str = Field(min_length=1, max_length=2000)
    client_request_id: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[a-zA-Z0-9_-]{1,64}$",
    )


class StartSessionResponse(BaseModel):
    session_id: str


@router.post(
    "/start",
    status_code=status.HTTP_201_CREATED,
    response_model=StartSessionResponse,
)
async def start_session(
    body: StartSessionBody,
    request: Request,
    response: Response,
) -> StartSessionResponse:
    """D13 + D13.5: backend ULID + per-client idempotency with TOCTOU lock.

    Status codes:
    - 201 Created: new session established
    - 200 OK: idempotency hit, returns existing session_id (no new session)
    - 409 Conflict: session_id already running (ULID collisions theoretical; safety net only)
    - 422 Unprocessable Entity: query / client_request_id validation failure
    """
    session_manager: SessionManager = request.app.state.session_manager

    # T11 D-TM: resolve inject directive before branching on client_request_id.
    # _is_test_request enforces double-guard; _parse_inject_directive strips
    # prefix from clean_query (NN2) so DB / LangGraph never see the test prefix.
    directive: InjectDirective | None = None
    clean_query: str = body.query
    if _is_test_request(request, get_settings()):
        directive, clean_query = _parse_inject_directive(body.query)

    # No client_request_id: no idempotency, create directly.
    if body.client_request_id is None:
        session_id = str(ULID())
        try:
            await session_manager.start_session(
                session_id=session_id,
                query=clean_query,
                inject_directive=directive,
            )
        except SessionAlreadyRunningError as exc:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Session {exc.session_id!r} is already running",
            ) from None
        if directive is not None:
            _INJECT_DIRECTIVES[session_id] = directive
        return StartSessionResponse(session_id=session_id)

    # Has client_request_id: per-key lock wraps read-await-write to prevent TOCTOU.
    # Concurrent requests with the same key block here; the second sees the cache hit
    # and returns 200 without creating a new session.
    lock = _IDEMPOTENCY_LOCKS.get(body.client_request_id)
    if lock is None:
        lock = asyncio.Lock()
        _IDEMPOTENCY_LOCKS[body.client_request_id] = lock

    async with lock:
        # Check inside lock (TOCTOU-safe).
        existing = _IDEMPOTENCY_CACHE.get(body.client_request_id)
        if existing is not None:
            response.status_code = status.HTTP_200_OK
            return StartSessionResponse(session_id=existing)

        # Create inside lock: concurrent same-key requests are serialized.
        session_id = str(ULID())
        try:
            await session_manager.start_session(
                session_id=session_id,
                query=clean_query,
                inject_directive=directive,
            )
        except SessionAlreadyRunningError as exc:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Session {exc.session_id!r} is already running",
            ) from None
        _IDEMPOTENCY_CACHE[body.client_request_id] = session_id
        if directive is not None:
            _INJECT_DIRECTIVES[session_id] = directive

    return StartSessionResponse(session_id=session_id)


@router.get("/demo-session-id", response_model=DemoSessionIdResponse)
async def demo_session_id_endpoint() -> DemoSessionIdResponse:
    """Return the demo replay session_id (loaded from fixture at startup).

    Public endpoint (no auth) — the session_id alone is not sensitive;
    the demo stream itself is gated by /research/{id}/stream's
    _is_demo_request_authorized guard.

    404 if no fixture is configured.
    """
    sid = _load_demo_session_id()
    if sid is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Demo replay fixture not configured",
        )
    return DemoSessionIdResponse(session_id=sid)


@router.get("/{session_id}/stream")
async def stream_session_endpoint(
    request: Request,
    session_id: Annotated[str, FastAPIPath(min_length=1, max_length=64)],
    last_event_id: Annotated[str | None, Header(alias="Last-Event-ID")] = None,
) -> StreamingResponse:
    """W3C SSE channel: replay-then-live for a research session.

    Pre-flight:
      - 404 if the session_id has no row in `lumen_research_sessions`
      - 400 if `Last-Event-ID` is provided but unknown (we don't
        silently replay-from-zero — the client MUST acknowledge a
        missing cursor)

    T13: if session_id matches the demo fixture, serve the replay path
    (gated by _is_demo_request_authorized three-tier guard).

    Headers:
      - Content-Type: text/event-stream
      - Cache-Control: no-cache (forbid intermediary caching)
      - X-Accel-Buffering: no (disable nginx response buffering — SSE
        frames must flush as soon as written)

    The endpoint never spawns a LangGraph producer (read-only path);
    the producer is owned by `POST /start` exclusively. A GET on a
    terminal session returns a finite replay then closes.
    """
    settings = get_settings()

    # T13: demo replay path — gated by D-DEMO three-tier guard
    demo_session_id = _load_demo_session_id()
    if demo_session_id is not None and session_id == demo_session_id:
        if not _is_demo_request_authorized(request, settings):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Demo replay requires demo origin, token, or testing mode",
            )
        return StreamingResponse(
            _replay_demo_session(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
            },
        )

    db_path = settings.LUMEN_DB_PATH

    last_seq = 0
    async with aiosqlite.connect(db_path) as conn:
        await configure_connection(conn)
        cur = await conn.execute(
            "SELECT 1 FROM lumen_research_sessions WHERE id = ?",
            (session_id,),
        )
        if (await cur.fetchone()) is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"session {session_id!r} not found",
            )
        # `is not None` (not truthiness): an empty header value `Last-Event-ID:`
        # means "provided but malformed", which is a client bug we surface as
        # 400 — silently falling back to last_seq=0 would misrepresent the
        # contract documented in this endpoint's docstring.
        if last_event_id is not None:
            stripped = last_event_id.strip()
            if not stripped:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Last-Event-ID header is present but empty",
                )
            resolved = await lookup_seq_by_event_id(conn, event_id=stripped)
            if resolved is None:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Unknown Last-Event-ID; client must reconnect without the header",
                )
            last_seq = resolved

    # T11: look up any inject directive stored by POST /start for this session.
    inject_directive = _INJECT_DIRECTIVES.get(session_id)

    return StreamingResponse(
        stream_session(
            session_id=session_id,
            db_path=db_path,
            last_seq=last_seq,
            inject_directive=inject_directive,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
